export const KAKAO_AUTHORIZE_WAITING = 'KAKAO_AUTHORIZE_WAITING';
export const KAKAO_AUTHORIZE_SUCCESS = 'KAKAO_AUTHORIZE_SUCCESS';
export const KAKAO_AUTHORIZE_FAILURE = 'KAKAO_AUTHORIZE_FAILURE';

export const AUTH_WAITING = 'AUTH_WAITING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
