export const KAKAO_AUTHORIZE_WAITING = 'KAKAO_AUTHORIZE_WAITING';
export const KAKAO_AUTHORIZE_SUCCESS = 'KAKAO_AUTHORIZE_SUCCESS';
export const KAKAO_AUTHORIZE_FAILURE = 'KAKAO_AUTHORIZE_FAILURE';

export const AUTH_WAITING = 'AUTH_WAITING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const GET_ME_WAITING = 'GET_ME_WAITING';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILURE = 'GET_ME_FAILURE';

export const ATTEND_WAITING = 'ATTEND_WAITING';
export const ATTEND_SUCCESS = 'ATTEND_SUCCESS';
export const ATTEND_FAILURE = 'ATTEND_FAILURE';

export const GET_ACCOUNT_WAITING = 'GET_ACCOUNT_WAITING';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = 'GET_ACCOUNT_FAILURE';

export const GET_TRANSACTION_WAITING = 'GET_TRANSACTION_WAITING';
export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS';
export const GET_TRANSACTION_FAILURE = 'GET_TRANSACTION_FAILURE';


export const GET_PRODUCT_WAITING = 'GET_PRODUCT_WAITING';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const GET_PRODUCT_DETAIL_WAITING = 'GET_PRODUCT_DETAIL_WAITING';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILURE = 'GET_PRODUCT_DETAIL_FAILURE';

export const GET_AIR_POLLUTION_WAITING = 'GET_AIR_POLLUTION_WAITING';
export const GET_AIR_POLLUTION_SUCCESS = 'GET_AIR_POLLUTION_SUCCESS';
export const GET_AIR_POLLUTION_FAILURE = 'GET_AIR_POLLUTION_FAILURE';

export const GET_DPM_SESSION_WAITING = 'GET_DPM_SESSION_WAITING';
export const GET_DPM_SESSION_SUCCESS = 'GET_DPM_SESSION_SUCCESS';
export const GET_DPM_SESSION_FAILURE = 'GET_DPM_SESSION_FAILURE';

export const GET_KAKAOTALK_WAITING = 'GET_KAKAOTALK_WAITING';
export const GET_KAKAOTALK_SUCCESS = 'GET_KAKAOTALK_SUCCESS';
export const GET_KAKAOTALK_FAILURE = 'GET_KAKAOTALK_FAILURE';


export const JOIN_PRODUCT_WAITING = 'JOIN_PRODUCT_WAITING';
export const JOIN_PRODUCT_SUCCESS = 'JOIN_PRODUCT_SUCCESS';
export const JOIN_PRODUCT_FAILURE = 'JOIN_PRODUCT_FAILURE';

export const GET_RANKING_WAITING = 'GET_RANKING_WAITING';
export const GET_RANKING_SUCCESS = 'GET_RANKING_SUCCESS';
export const GET_RANKING_FAILURE = 'GET_RANKING_FAILURE';